//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnoLisClient.UI.UnoLisServerReference.Login {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthCredentials", Namespace="http://schemas.datacontract.org/2004/07/UnoLisServer.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class AuthCredentials : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponseOfanyType", Namespace="http://schemas.datacontract.org/2004/07/UnoLisServer.Common.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UnoLisClient.UI.UnoLisServerReference.Login.AuthCredentials))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UnoLisClient.UI.UnoLisServerReference.Login.MessageCode))]
    public partial class ServiceResponseOfanyType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnoLisClient.UI.UnoLisServerReference.Login.MessageCode CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnoLisClient.UI.UnoLisServerReference.Login.MessageCode Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageCode", Namespace="http://schemas.datacontract.org/2004/07/UnoLisServer.Common.Enums")]
    public enum MessageCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegistrationSuccessful = 1001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoginSuccessful = 1002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LogoutSuccessful = 1003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProfileDataRetrieved = 1004,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProfileUpdated = 1005,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FriendRequestSent = 1006,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FriendRequestAccepted = 1007,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FriendRemoved = 1008,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChatMessageSent = 1009,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChatMessageRetrieved = 1010,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyCreated = 1011,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyJoined = 1012,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyLeft = 1013,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatchStarted = 1014,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatchEnded = 1015,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BadRequest = 2000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidData = 2001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCredentials = 2002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NicknameAlreadyTaken = 2003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmailAlreadyRegistered = 2004,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmailFormat = 2005,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WeakPassword = 2006,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerNotFound = 2007,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SamePassword = 2008,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmptyMessage = 2009,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MessageTooLong = 2010,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InappropriateContent = 2011,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AlreadyFriends = 2012,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PendingFriendRequest = 2013,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidSocialUrl = 2014,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BlockedUser = 2015,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyNotFound = 2016,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyFull = 2017,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OperationNotSupported = 2018,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValidationFailed = 2019,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmptyFields = 2020,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SessionExpired = 3000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnauthorizedAccess = 3001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidToken = 3002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissingToken = 3003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicateSession = 3004,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserNotConnected = 3005,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoginInternalError = 3006,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LogoutInternalError = 3007,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseError = 4000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TransactionFailed = 4001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SqlError = 4002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConcurrencyConflict = 4003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SerializationError = 4004,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnhandledException = 4005,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CallbackError = 4006,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProfileUpdateFailed = 4007,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProfileFetchFailed = 4008,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChatInternalError = 4009,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FriendsInternalError = 4010,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyInternalError = 4011,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeneralServerError = 4012,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConnectionLost = 5000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Timeout = 5001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConnectionFailed = 5002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConnectionRejected = 5003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnstableConnection = 5004,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClientDisconnected = 5005,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FriendActionCompleted = 6000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerBlocked = 6001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerUnblocked = 6002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerHasActiveLobby = 6003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerNotInLobby = 6004,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerAlreadyReady = 6005,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerNotReady = 6006,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatchAlreadyStarted = 6007,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatchCancelled = 6008,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatchNotFound = 6009,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatchAlreadyEnded = 6010,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerKicked = 6011,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerBanned = 6012,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyClosed = 6013,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoPermissions = 6014,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyInconsistentState = 6015,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerDisconnected = 6016,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerReconnected = 6017,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatchResultsRecorded = 6018,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RewardProcessingError = 6019,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PurchaseProcessingError = 6020,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UnoLisServerReference.Login.ILoginManager", CallbackContract=typeof(UnoLisClient.UI.UnoLisServerReference.Login.ILoginManagerCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface ILoginManager {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILoginManager/Login")]
        void Login(UnoLisClient.UI.UnoLisServerReference.Login.AuthCredentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILoginManager/Login")]
        System.Threading.Tasks.Task LoginAsync(UnoLisClient.UI.UnoLisServerReference.Login.AuthCredentials credentials);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginManagerCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginManager/LoginResponse", ReplyAction="http://tempuri.org/ILoginManager/LoginResponseResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UnoLisClient.UI.UnoLisServerReference.Login.AuthCredentials))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UnoLisServer.Common.Enums.MessageCode))]
        void LoginResponse(UnoLisServer.Common.Models.ServiceResponse<object> response);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginManagerChannel : UnoLisClient.UI.UnoLisServerReference.Login.ILoginManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginManagerClient : System.ServiceModel.DuplexClientBase<UnoLisClient.UI.UnoLisServerReference.Login.ILoginManager>, UnoLisClient.UI.UnoLisServerReference.Login.ILoginManager {
        
        public LoginManagerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public LoginManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public LoginManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LoginManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LoginManagerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Login(UnoLisClient.UI.UnoLisServerReference.Login.AuthCredentials credentials) {
            base.Channel.Login(credentials);
        }
        
        public System.Threading.Tasks.Task LoginAsync(UnoLisClient.UI.UnoLisServerReference.Login.AuthCredentials credentials) {
            return base.Channel.LoginAsync(credentials);
        }
    }
}
