//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnoLisClient.Logic.UnoLisServerReference.Gameplay {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayCardData", Namespace="http://schemas.datacontract.org/2004/07/UnoLisServer.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class PlayCardData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LobbyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SelectedColorIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardId {
            get {
                return this.CardIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CardIdField, value) != true)) {
                    this.CardIdField = value;
                    this.RaisePropertyChanged("CardId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LobbyCode {
            get {
                return this.LobbyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LobbyCodeField, value) != true)) {
                    this.LobbyCodeField = value;
                    this.RaisePropertyChanged("LobbyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SelectedColorId {
            get {
                return this.SelectedColorIdField;
            }
            set {
                if ((this.SelectedColorIdField.Equals(value) != true)) {
                    this.SelectedColorIdField = value;
                    this.RaisePropertyChanged("SelectedColorId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Card", Namespace="http://schemas.datacontract.org/2004/07/UnoLisServer.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class Card : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnoLisClient.Logic.UnoLisServerReference.Gameplay.CardColor ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnoLisClient.Logic.UnoLisServerReference.Gameplay.CardValue ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnoLisClient.Logic.UnoLisServerReference.Gameplay.CardColor Color {
            get {
                return this.ColorField;
            }
            set {
                if ((this.ColorField.Equals(value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnoLisClient.Logic.UnoLisServerReference.Gameplay.CardValue Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardColor", Namespace="http://schemas.datacontract.org/2004/07/UnoLisServer.Contracts.Enums")]
    public enum CardColor : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Red = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yellow = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Green = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Blue = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wild = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardValue", Namespace="http://schemas.datacontract.org/2004/07/UnoLisServer.Contracts.Enums")]
    public enum CardValue : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Zero = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        One = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Two = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Three = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Four = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Five = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Six = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Seven = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Eight = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nine = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Skip = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reverse = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DrawTwo = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wild = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WildDrawFour = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WildDrawTen = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WildDrawSkipReverseFour = 16,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultData", Namespace="http://schemas.datacontract.org/2004/07/UnoLisServer.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class ResultData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvatarNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvatarName {
            get {
                return this.AvatarNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarNameField, value) != true)) {
                    this.AvatarNameField = value;
                    this.RaisePropertyChanged("AvatarName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rank {
            get {
                return this.RankField;
            }
            set {
                if ((this.RankField.Equals(value) != true)) {
                    this.RankField = value;
                    this.RaisePropertyChanged("Rank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GamePlayer", Namespace="http://schemas.datacontract.org/2004/07/UnoLisServer.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class GamePlayer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvatarNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CardCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsConnectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvatarName {
            get {
                return this.AvatarNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarNameField, value) != true)) {
                    this.AvatarNameField = value;
                    this.RaisePropertyChanged("AvatarName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CardCount {
            get {
                return this.CardCountField;
            }
            set {
                if ((this.CardCountField.Equals(value) != true)) {
                    this.CardCountField = value;
                    this.RaisePropertyChanged("CardCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsConnected {
            get {
                return this.IsConnectedField;
            }
            set {
                if ((this.IsConnectedField.Equals(value) != true)) {
                    this.IsConnectedField = value;
                    this.RaisePropertyChanged("IsConnected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UnoLisServerReference.Gameplay.IGameplayManager", CallbackContract=typeof(UnoLisClient.Logic.UnoLisServerReference.Gameplay.IGameplayManagerCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IGameplayManager {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameplayManager/PlayCard")]
        void PlayCard(UnoLisClient.Logic.UnoLisServerReference.Gameplay.PlayCardData data);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameplayManager/PlayCard")]
        System.Threading.Tasks.Task PlayCardAsync(UnoLisClient.Logic.UnoLisServerReference.Gameplay.PlayCardData data);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameplayManager/DrawCard")]
        void DrawCard(string lobbyCode, string nickname);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameplayManager/DrawCard")]
        System.Threading.Tasks.Task DrawCardAsync(string lobbyCode, string nickname);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameplayManager/ConnectToGame")]
        void ConnectToGame(string lobbyCode, string nickname);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameplayManager/ConnectToGame")]
        System.Threading.Tasks.Task ConnectToGameAsync(string lobbyCode, string nickname);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameplayManager/SayUnoAsync")]
        void SayUnoAsync(string lobbyCode, string nickname);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameplayManager/SayUnoAsync")]
        System.Threading.Tasks.Task SayUnoAsyncAsync(string lobbyCode, string nickname);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameplayManager/DisconnectPlayer")]
        void DisconnectPlayer(string lobbyCode, string nickname);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameplayManager/DisconnectPlayer")]
        System.Threading.Tasks.Task DisconnectPlayerAsync(string lobbyCode, string nickname);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameplayManager/LeaveGame")]
        void LeaveGame(string lobbyCode, string nickname);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameplayManager/LeaveGame")]
        System.Threading.Tasks.Task LeaveGameAsync(string lobbyCode, string nickname);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameplayManager/UseItem")]
        void UseItem(string lobbyCode, string nickname, UnoLisServer.Common.Enums.ItemType itemType, string targetNickname);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameplayManager/UseItem")]
        System.Threading.Tasks.Task UseItemAsync(string lobbyCode, string nickname, UnoLisServer.Common.Enums.ItemType itemType, string targetNickname);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameplayManagerCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameplayManager/CardPlayed")]
        void CardPlayed(string nickname, UnoLisClient.Logic.UnoLisServerReference.Gameplay.Card card, int cardsLeft);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameplayManager/CardDrawn")]
        void CardDrawn(string nickname, int cardsLeft);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameplayManager/TurnChanged")]
        void TurnChanged(string nextPlayerNickname);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameplayManager/MatchEnded")]
        void MatchEnded(UnoLisClient.Logic.UnoLisServerReference.Gameplay.ResultData[] results);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameplayManager/ReceiveInitialHand")]
        void ReceiveInitialHand(UnoLisClient.Logic.UnoLisServerReference.Gameplay.Card[] hand);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameplayManager/ReceiveCards")]
        void ReceiveCards(UnoLisClient.Logic.UnoLisServerReference.Gameplay.Card[] cards);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameplayManager/ReceivePlayerList")]
        void ReceivePlayerList(UnoLisClient.Logic.UnoLisServerReference.Gameplay.GamePlayer[] players);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameplayManager/GameMessage")]
        void GameMessage(string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameplayManager/PlayerShoutedUno")]
        void PlayerShoutedUno(string nickname);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameplayManager/PlayerUsedItem")]
        void PlayerUsedItem(string nickname, UnoLisServer.Common.Enums.ItemType itemType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameplayManagerChannel : UnoLisClient.Logic.UnoLisServerReference.Gameplay.IGameplayManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameplayManagerClient : System.ServiceModel.DuplexClientBase<UnoLisClient.Logic.UnoLisServerReference.Gameplay.IGameplayManager>, UnoLisClient.Logic.UnoLisServerReference.Gameplay.IGameplayManager {
        
        public GameplayManagerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GameplayManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GameplayManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameplayManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameplayManagerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void PlayCard(UnoLisClient.Logic.UnoLisServerReference.Gameplay.PlayCardData data) {
            base.Channel.PlayCard(data);
        }
        
        public System.Threading.Tasks.Task PlayCardAsync(UnoLisClient.Logic.UnoLisServerReference.Gameplay.PlayCardData data) {
            return base.Channel.PlayCardAsync(data);
        }
        
        public void DrawCard(string lobbyCode, string nickname) {
            base.Channel.DrawCard(lobbyCode, nickname);
        }
        
        public System.Threading.Tasks.Task DrawCardAsync(string lobbyCode, string nickname) {
            return base.Channel.DrawCardAsync(lobbyCode, nickname);
        }
        
        public void ConnectToGame(string lobbyCode, string nickname) {
            base.Channel.ConnectToGame(lobbyCode, nickname);
        }
        
        public System.Threading.Tasks.Task ConnectToGameAsync(string lobbyCode, string nickname) {
            return base.Channel.ConnectToGameAsync(lobbyCode, nickname);
        }
        
        public void SayUnoAsync(string lobbyCode, string nickname) {
            base.Channel.SayUnoAsync(lobbyCode, nickname);
        }
        
        public System.Threading.Tasks.Task SayUnoAsyncAsync(string lobbyCode, string nickname) {
            return base.Channel.SayUnoAsyncAsync(lobbyCode, nickname);
        }
        
        public void DisconnectPlayer(string lobbyCode, string nickname) {
            base.Channel.DisconnectPlayer(lobbyCode, nickname);
        }
        
        public System.Threading.Tasks.Task DisconnectPlayerAsync(string lobbyCode, string nickname) {
            return base.Channel.DisconnectPlayerAsync(lobbyCode, nickname);
        }
        
        public void LeaveGame(string lobbyCode, string nickname) {
            base.Channel.LeaveGame(lobbyCode, nickname);
        }
        
        public System.Threading.Tasks.Task LeaveGameAsync(string lobbyCode, string nickname) {
            return base.Channel.LeaveGameAsync(lobbyCode, nickname);
        }
        
        public void UseItem(string lobbyCode, string nickname, UnoLisServer.Common.Enums.ItemType itemType, string targetNickname) {
            base.Channel.UseItem(lobbyCode, nickname, itemType, targetNickname);
        }
        
        public System.Threading.Tasks.Task UseItemAsync(string lobbyCode, string nickname, UnoLisServer.Common.Enums.ItemType itemType, string targetNickname) {
            return base.Channel.UseItemAsync(lobbyCode, nickname, itemType, targetNickname);
        }
    }
}
