//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnoLisClient.Logic.UnoLisServerReference.LobbyDuplex {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UnoLisServerReference.LobbyDuplex.ILobbyDuplexManager", CallbackContract=typeof(UnoLisClient.Logic.UnoLisServerReference.LobbyDuplex.ILobbyDuplexManagerCallback))]
    public interface ILobbyDuplexManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyDuplexManager/ConnectToLobby", ReplyAction="http://tempuri.org/ILobbyDuplexManager/ConnectToLobbyResponse")]
        void ConnectToLobby(string lobbyCode, string nickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyDuplexManager/ConnectToLobby", ReplyAction="http://tempuri.org/ILobbyDuplexManager/ConnectToLobbyResponse")]
        System.Threading.Tasks.Task ConnectToLobbyAsync(string lobbyCode, string nickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyDuplexManager/DisconnectFromLobby", ReplyAction="http://tempuri.org/ILobbyDuplexManager/DisconnectFromLobbyResponse")]
        void DisconnectFromLobby(string lobbyCode, string nickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyDuplexManager/DisconnectFromLobby", ReplyAction="http://tempuri.org/ILobbyDuplexManager/DisconnectFromLobbyResponse")]
        System.Threading.Tasks.Task DisconnectFromLobbyAsync(string lobbyCode, string nickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyDuplexManager/SetReadyStatus", ReplyAction="http://tempuri.org/ILobbyDuplexManager/SetReadyStatusResponse")]
        void SetReadyStatus(string lobbyCode, string nickname, bool isReady);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyDuplexManager/SetReadyStatus", ReplyAction="http://tempuri.org/ILobbyDuplexManager/SetReadyStatusResponse")]
        System.Threading.Tasks.Task SetReadyStatusAsync(string lobbyCode, string nickname, bool isReady);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILobbyDuplexManagerCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyDuplexManager/PlayerJoined")]
        void PlayerJoined(string nickname);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyDuplexManager/PlayerLeft")]
        void PlayerLeft(string nickname);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyDuplexManager/UpdatePlayerList")]
        void UpdatePlayerList(string[] nicknames);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyDuplexManager/PlayerReadyStatusChanged")]
        void PlayerReadyStatusChanged(string nickname, bool isReady);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILobbyDuplexManagerChannel : UnoLisClient.Logic.UnoLisServerReference.LobbyDuplex.ILobbyDuplexManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LobbyDuplexManagerClient : System.ServiceModel.DuplexClientBase<UnoLisClient.Logic.UnoLisServerReference.LobbyDuplex.ILobbyDuplexManager>, UnoLisClient.Logic.UnoLisServerReference.LobbyDuplex.ILobbyDuplexManager {
        
        public LobbyDuplexManagerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public LobbyDuplexManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public LobbyDuplexManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LobbyDuplexManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LobbyDuplexManagerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void ConnectToLobby(string lobbyCode, string nickname) {
            base.Channel.ConnectToLobby(lobbyCode, nickname);
        }
        
        public System.Threading.Tasks.Task ConnectToLobbyAsync(string lobbyCode, string nickname) {
            return base.Channel.ConnectToLobbyAsync(lobbyCode, nickname);
        }
        
        public void DisconnectFromLobby(string lobbyCode, string nickname) {
            base.Channel.DisconnectFromLobby(lobbyCode, nickname);
        }
        
        public System.Threading.Tasks.Task DisconnectFromLobbyAsync(string lobbyCode, string nickname) {
            return base.Channel.DisconnectFromLobbyAsync(lobbyCode, nickname);
        }
        
        public void SetReadyStatus(string lobbyCode, string nickname, bool isReady) {
            base.Channel.SetReadyStatus(lobbyCode, nickname, isReady);
        }
        
        public System.Threading.Tasks.Task SetReadyStatusAsync(string lobbyCode, string nickname, bool isReady) {
            return base.Channel.SetReadyStatusAsync(lobbyCode, nickname, isReady);
        }
    }
}
