//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnoLisClient.UI.UnoLisServerReference.ProfileEdit {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfileData", Namespace="http://schemas.datacontract.org/2004/07/UnoLisServer.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class ProfileData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentAvatarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExperiencePointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacebookUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstagramUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LossesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchesPlayedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxStreakField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StreakField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TikTokUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WinsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentAvatar {
            get {
                return this.CurrentAvatarField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentAvatarField, value) != true)) {
                    this.CurrentAvatarField = value;
                    this.RaisePropertyChanged("CurrentAvatar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExperiencePoints {
            get {
                return this.ExperiencePointsField;
            }
            set {
                if ((this.ExperiencePointsField.Equals(value) != true)) {
                    this.ExperiencePointsField = value;
                    this.RaisePropertyChanged("ExperiencePoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacebookUrl {
            get {
                return this.FacebookUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.FacebookUrlField, value) != true)) {
                    this.FacebookUrlField = value;
                    this.RaisePropertyChanged("FacebookUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstagramUrl {
            get {
                return this.InstagramUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.InstagramUrlField, value) != true)) {
                    this.InstagramUrlField = value;
                    this.RaisePropertyChanged("InstagramUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Level {
            get {
                return this.LevelField;
            }
            set {
                if ((this.LevelField.Equals(value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Losses {
            get {
                return this.LossesField;
            }
            set {
                if ((this.LossesField.Equals(value) != true)) {
                    this.LossesField = value;
                    this.RaisePropertyChanged("Losses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchesPlayed {
            get {
                return this.MatchesPlayedField;
            }
            set {
                if ((this.MatchesPlayedField.Equals(value) != true)) {
                    this.MatchesPlayedField = value;
                    this.RaisePropertyChanged("MatchesPlayed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxStreak {
            get {
                return this.MaxStreakField;
            }
            set {
                if ((this.MaxStreakField.Equals(value) != true)) {
                    this.MaxStreakField = value;
                    this.RaisePropertyChanged("MaxStreak");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Streak {
            get {
                return this.StreakField;
            }
            set {
                if ((this.StreakField.Equals(value) != true)) {
                    this.StreakField = value;
                    this.RaisePropertyChanged("Streak");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TikTokUrl {
            get {
                return this.TikTokUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.TikTokUrlField, value) != true)) {
                    this.TikTokUrlField = value;
                    this.RaisePropertyChanged("TikTokUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Wins {
            get {
                return this.WinsField;
            }
            set {
                if ((this.WinsField.Equals(value) != true)) {
                    this.WinsField = value;
                    this.RaisePropertyChanged("Wins");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UnoLisServerReference.ProfileEdit.IProfileEditManager", CallbackContract=typeof(UnoLisClient.UI.UnoLisServerReference.ProfileEdit.IProfileEditManagerCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IProfileEditManager {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IProfileEditManager/UpdateProfileData")]
        void UpdateProfileData(UnoLisClient.UI.UnoLisServerReference.ProfileEdit.ProfileData data);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IProfileEditManager/UpdateProfileData")]
        System.Threading.Tasks.Task UpdateProfileDataAsync(UnoLisClient.UI.UnoLisServerReference.ProfileEdit.ProfileData data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfileEditManagerCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileEditManager/ProfileUpdateResponse", ReplyAction="http://tempuri.org/IProfileEditManager/ProfileUpdateResponseResponse")]
        void ProfileUpdateResponse(UnoLisServer.Common.Models.ServiceResponse<UnoLisClient.UI.UnoLisServerReference.ProfileEdit.ProfileData> response);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfileEditManagerChannel : UnoLisClient.UI.UnoLisServerReference.ProfileEdit.IProfileEditManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProfileEditManagerClient : System.ServiceModel.DuplexClientBase<UnoLisClient.UI.UnoLisServerReference.ProfileEdit.IProfileEditManager>, UnoLisClient.UI.UnoLisServerReference.ProfileEdit.IProfileEditManager {
        
        public ProfileEditManagerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ProfileEditManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ProfileEditManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileEditManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileEditManagerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void UpdateProfileData(UnoLisClient.UI.UnoLisServerReference.ProfileEdit.ProfileData data) {
            base.Channel.UpdateProfileData(data);
        }
        
        public System.Threading.Tasks.Task UpdateProfileDataAsync(UnoLisClient.UI.UnoLisServerReference.ProfileEdit.ProfileData data) {
            return base.Channel.UpdateProfileDataAsync(data);
        }
    }
}
