//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnoLisClient.UI.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnoLisClient.UI.Properties.Langs.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error.
        /// </summary>
        public static string ConnectionErrorHeaderLabel {
            get {
                return ResourceManager.GetString("ConnectionErrorHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect with the server. Check your internet connection and try again..
        /// </summary>
        public static string ConnectionErrorMessageLabel {
            get {
                return ResourceManager.GetString("ConnectionErrorMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string EmailEmptyMessageLabel {
            get {
                return ResourceManager.GetString("EmailEmptyMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email format is invalid..
        /// </summary>
        public static string EmailFormatMessageLabel {
            get {
                return ResourceManager.GetString("EmailFormatMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name is required..
        /// </summary>
        public static string FullNameEmptyMessageLabel {
            get {
                return ResourceManager.GetString("FullNameEmptyMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name can&apos;t exceed {0} characters..
        /// </summary>
        public static string FullNameLengthMessageLabel {
            get {
                return ResourceManager.GetString("FullNameLengthMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password can&apos;t be empty..
        /// </summary>
        public static string NewPasswordEmptyMessageLabel {
            get {
                return ResourceManager.GetString("NewPasswordEmptyMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname is required..
        /// </summary>
        public static string NicknameEmptyMessageLabel {
            get {
                return ResourceManager.GetString("NicknameEmptyMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The nickname must contain letters, numbers, hyphens and underscores..
        /// </summary>
        public static string NicknameFormatMessageLabel {
            get {
                return ResourceManager.GetString("NicknameFormatMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The nickname length must be between {0} and {1} characters..
        /// </summary>
        public static string NicknameLengthMessageLabel {
            get {
                return ResourceManager.GetString("NicknameLengthMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game is currently unavailable, please try again later..
        /// </summary>
        public static string NoConnectionMessageLabel {
            get {
                return ResourceManager.GetString("NoConnectionMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match, please verify them..
        /// </summary>
        public static string PasswordDontMatchLabel {
            get {
                return ResourceManager.GetString("PasswordDontMatchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string PasswordEmptyMessageLabel {
            get {
                return ResourceManager.GetString("PasswordEmptyMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password length must be between {0} and {1} characters..
        /// </summary>
        public static string PasswordLengthMessageLabel {
            get {
                return ResourceManager.GetString("PasswordLengthMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password is the same as the old one..
        /// </summary>
        public static string PasswordSameAsOldMessageLabel {
            get {
                return ResourceManager.GetString("PasswordSameAsOldMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL must belong to the {0} domain..
        /// </summary>
        public static string SocialLinkDomainMessageLabel {
            get {
                return ResourceManager.GetString("SocialLinkDomainMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} link is not a valid URL..
        /// </summary>
        public static string SocialLinkFormatMessageLabel {
            get {
                return ResourceManager.GetString("SocialLinkFormatMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user with the nickname given already exists..
        /// </summary>
        public static string UserDuplicatedLabel {
            get {
                return ResourceManager.GetString("UserDuplicatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password is not secure, please check the requirements..
        /// </summary>
        public static string WeakPasswordMessageLabel {
            get {
                return ResourceManager.GetString("WeakPasswordMessageLabel", resourceCulture);
            }
        }
    }
}
