//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnoLisClient.UI.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnoLisClient.UI.Properties.Langs.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account with the email {0} is not verified..
        /// </summary>
        public static string AccountNotVerifiedMessageLabel {
            get {
                return ResourceManager.GetString("AccountNotVerifiedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already on your friends list..
        /// </summary>
        public static string AlreadyFriendsMessageLabel {
            get {
                return ResourceManager.GetString("AlreadyFriendsMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve recently reported {0}. Please try again later..
        /// </summary>
        public static string AlreadyReportedRecentlyMessageLabel {
            get {
                return ResourceManager.GetString("AlreadyReportedRecentlyMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must unlock this avatar before using it..
        /// </summary>
        public static string AvatarLockedMessageLabel {
            get {
                return ResourceManager.GetString("AvatarLockedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete or incorrectly formatted request. Please verify the information or contact support..
        /// </summary>
        public static string BadRequestMessageLabel {
            get {
                return ResourceManager.GetString("BadRequestMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t send messages to a blocked user..
        /// </summary>
        public static string BlockedUserMessageLabel {
            get {
                return ResourceManager.GetString("BlockedUserMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing client callback..
        /// </summary>
        public static string CallbackErrorMessageLabel {
            get {
                return ResourceManager.GetString("CallbackErrorMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t add yourself as a friend..
        /// </summary>
        public static string CannotAddSelfMessageLabel {
            get {
                return ResourceManager.GetString("CannotAddSelfMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error in the chat module..
        /// </summary>
        public static string ChatInternalErrorMessageLabel {
            get {
                return ResourceManager.GetString("ChatInternalErrorMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client was disconnected from the remote service..
        /// </summary>
        public static string ClientDisconnectedMessageLabel {
            get {
                return ResourceManager.GetString("ClientDisconnectedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data conflict or concurrency..
        /// </summary>
        public static string ConcurrencyConflictMessageLabel {
            get {
                return ResourceManager.GetString("ConcurrencyConflictMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error in the verification code module..
        /// </summary>
        public static string ConfirmationInternalErrorMessageLabel {
            get {
                return ResourceManager.GetString("ConfirmationInternalErrorMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error.
        /// </summary>
        public static string ConnectionErrorHeaderLabel {
            get {
                return ResourceManager.GetString("ConnectionErrorHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect with the server. Check your internet connection and try again..
        /// </summary>
        public static string ConnectionErrorMessageLabel {
            get {
                return ResourceManager.GetString("ConnectionErrorMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server refused the connection..
        /// </summary>
        public static string ConnectionRejectedMessageLabel {
            get {
                return ResourceManager.GetString("ConnectionRejectedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database error..
        /// </summary>
        public static string DatabaseErrorMessageLabel {
            get {
                return ResourceManager.GetString("DatabaseErrorMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your deck of cards is empty..
        /// </summary>
        public static string DeckIsEmptyMessageLabel {
            get {
                return ResourceManager.GetString("DeckIsEmptyMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is not logged in..
        /// </summary>
        public static string DuplicateSessionMessageLabel {
            get {
                return ResourceManager.GetString("DuplicateSessionMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address provided is already in use. Please provide another one..
        /// </summary>
        public static string EmailAlreadyRegisteredMessageLabel {
            get {
                return ResourceManager.GetString("EmailAlreadyRegisteredMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string EmailEmptyMessageLabel {
            get {
                return ResourceManager.GetString("EmailEmptyMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email format is invalid..
        /// </summary>
        public static string EmailFormatMessageLabel {
            get {
                return ResourceManager.GetString("EmailFormatMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending email, please try again or contact an administrator..
        /// </summary>
        public static string EmailSendingFailedMessageLabel {
            get {
                return ResourceManager.GetString("EmailSendingFailedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more required fields are empty..
        /// </summary>
        public static string EmptyFieldsMessageLabel {
            get {
                return ResourceManager.GetString("EmptyFieldsMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading file, please contact an administrator..
        /// </summary>
        public static string FileSystemErrorMessageLabel {
            get {
                return ResourceManager.GetString("FileSystemErrorMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} forgot to say “UNO.” Draw {1}!.
        /// </summary>
        public static string ForgotToCallUnoMessageLabel {
            get {
                return ResourceManager.GetString("ForgotToCallUnoMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend action completed..
        /// </summary>
        public static string FriendActionCompletedMessageLabel {
            get {
                return ResourceManager.GetString("FriendActionCompletedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No friend request found for {0}..
        /// </summary>
        public static string FriendRequestNotFoundMessageLabel {
            get {
                return ResourceManager.GetString("FriendRequestNotFoundMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error in the friends module..
        /// </summary>
        public static string FriendsInternalErrorMessageLabel {
            get {
                return ResourceManager.GetString("FriendsInternalErrorMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name is required..
        /// </summary>
        public static string FullNameEmptyMessageLabel {
            get {
                return ResourceManager.GetString("FullNameEmptyMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name can&apos;t exceed {0} characters..
        /// </summary>
        public static string FullNameLengthMessageLabel {
            get {
                return ResourceManager.GetString("FullNameLengthMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General server error..
        /// </summary>
        public static string GeneralServerErrorMessageLabel {
            get {
                return ResourceManager.GetString("GeneralServerErrorMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message contains inappropriate language..
        /// </summary>
        public static string InappropriatedContentMessageLabel {
            get {
                return ResourceManager.GetString("InappropriatedContentMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot select that avatar. Try another one..
        /// </summary>
        public static string InvalidAvatarSelectionMessageLabel {
            get {
                return ResourceManager.GetString("InvalidAvatarSelectionMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password, please verify the fields..
        /// </summary>
        public static string InvalidCredentialsMessageLabel {
            get {
                return ResourceManager.GetString("InvalidCredentialsMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more fields contain invalid data. Please verify the information provided..
        /// </summary>
        public static string InvalidDataMessageLabel {
            get {
                return ResourceManager.GetString("InvalidDataMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was not found in your friends list..
        /// </summary>
        public static string InvalidSearchQueryMessageLabel {
            get {
                return ResourceManager.GetString("InvalidSearchQueryMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid authentication token..
        /// </summary>
        public static string InvalidTokenMessageLabel {
            get {
                return ResourceManager.GetString("InvalidTokenMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item is not in the store....
        /// </summary>
        public static string ItemNotInShopMessageLabel {
            get {
                return ResourceManager.GetString("ItemNotInShopMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The match was closed by the host..
        /// </summary>
        public static string LobbyClosedMessageLabel {
            get {
                return ResourceManager.GetString("LobbyClosedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lobby already has the maximum number of players allowed (4)..
        /// </summary>
        public static string LobbyFullMessageLabel {
            get {
                return ResourceManager.GetString("LobbyFullMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistent lobby state detected..
        /// </summary>
        public static string LobbyInconsistentStateMessageLabel {
            get {
                return ResourceManager.GetString("LobbyInconsistentStateMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error in the game/lobby module..
        /// </summary>
        public static string LobbyInternalErrorMessageLabel {
            get {
                return ResourceManager.GetString("LobbyInternalErrorMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested lobby couldn&apos;t be found..
        /// </summary>
        public static string LobbyNotFoundMessageLabel {
            get {
                return ResourceManager.GetString("LobbyNotFoundMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error during login..
        /// </summary>
        public static string LoginInternalErrorMessageLabel {
            get {
                return ResourceManager.GetString("LoginInternalErrorMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error during logout..
        /// </summary>
        public static string LogoutInternalErrorMessageLabel {
            get {
                return ResourceManager.GetString("LogoutInternalErrorMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game is over now..
        /// </summary>
        public static string MatchAlreadyEndedMessageLabel {
            get {
                return ResourceManager.GetString("MatchAlreadyEndedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t join, the game has already started..
        /// </summary>
        public static string MatchAlreadyStartedMessageLabel {
            get {
                return ResourceManager.GetString("MatchAlreadyStartedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The match {0} has been canceled..
        /// </summary>
        public static string MatchCancelledMessageLabel {
            get {
                return ResourceManager.GetString("MatchCancelledMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The match with code {0} was not found..
        /// </summary>
        public static string MatchNotFoundMessageLabel {
            get {
                return ResourceManager.GetString("MatchNotFoundMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t send an empty message..
        /// </summary>
        public static string MessageCantBeEmptyMessageLabel {
            get {
                return ResourceManager.GetString("MessageCantBeEmptyMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message exceeds the allowed character limit (200)..
        /// </summary>
        public static string MessageLengthMessageLabel {
            get {
                return ResourceManager.GetString("MessageLengthMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A session token was not provided..
        /// </summary>
        public static string MissingTokenMessageLabel {
            get {
                return ResourceManager.GetString("MissingTokenMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First, you must draw cards..
        /// </summary>
        public static string MustDrawCardsMessageLabel {
            get {
                return ResourceManager.GetString("MustDrawCardsMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First, you must play a card or draw one..
        /// </summary>
        public static string MustPlayOrDrawMessageLabel {
            get {
                return ResourceManager.GetString("MustPlayOrDrawMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password can&apos;t be empty..
        /// </summary>
        public static string NewPasswordEmptyMessageLabel {
            get {
                return ResourceManager.GetString("NewPasswordEmptyMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account with the associated nickname already exists..
        /// </summary>
        public static string NicknameAlreadyTakenMessageLabel {
            get {
                return ResourceManager.GetString("NicknameAlreadyTakenMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname is required..
        /// </summary>
        public static string NicknameEmptyMessageLabel {
            get {
                return ResourceManager.GetString("NicknameEmptyMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The nickname must contain letters, numbers, hyphens and underscores..
        /// </summary>
        public static string NicknameFormatMessageLabel {
            get {
                return ResourceManager.GetString("NicknameFormatMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The nickname length must be between {0} and {1} characters..
        /// </summary>
        public static string NicknameLengthMessageLabel {
            get {
                return ResourceManager.GetString("NicknameLengthMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must change your profile information before saving..
        /// </summary>
        public static string NoChangesMessageLabel {
            get {
                return ResourceManager.GetString("NoChangesMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game is currently unavailable, please try again later..
        /// </summary>
        public static string NoConnectionMessageLabel {
            get {
                return ResourceManager.GetString("NoConnectionMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to execute this action..
        /// </summary>
        public static string NoPermissionsMessageLabel {
            get {
                return ResourceManager.GetString("NoPermissionsMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough Revo coins, please get more..
        /// </summary>
        public static string NotEnoughCurrencyMessageLabel {
            get {
                return ResourceManager.GetString("NotEnoughCurrencyMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s not your turn to play a card..
        /// </summary>
        public static string NotPlayerTurnMessageLabel {
            get {
                return ResourceManager.GetString("NotPlayerTurnMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation not supported..
        /// </summary>
        public static string OperationNotSupportedMessageLabel {
            get {
                return ResourceManager.GetString("OperationNotSupportedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match, please verify them..
        /// </summary>
        public static string PasswordDontMatchMessageLabel {
            get {
                return ResourceManager.GetString("PasswordDontMatchMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string PasswordEmptyMessageLabel {
            get {
                return ResourceManager.GetString("PasswordEmptyMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password length must be between {0} and {1} characters..
        /// </summary>
        public static string PasswordLengthMessageLabel {
            get {
                return ResourceManager.GetString("PasswordLengthMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password is the same as the old one..
        /// </summary>
        public static string PasswordSameAsOldMessageLabel {
            get {
                return ResourceManager.GetString("PasswordSameAsOldMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a friend request for {0}..
        /// </summary>
        public static string PendingFriendRequestMessageLabel {
            get {
                return ResourceManager.GetString("PendingFriendRequestMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player was already ready..
        /// </summary>
        public static string PlayerAlreadyReadyMessageLabel {
            get {
                return ResourceManager.GetString("PlayerAlreadyReadyMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} disconnected during the match..
        /// </summary>
        public static string PlayerDisconnectedMessageLabel {
            get {
                return ResourceManager.GetString("PlayerDisconnectedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player already has an active lobby..
        /// </summary>
        public static string PlayerHasActiveLobbyMessageLabel {
            get {
                return ResourceManager.GetString("PlayerHasActiveLobbyMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more than 4 players can be added to the match..
        /// </summary>
        public static string PlayerLimitReachedMessageLabel {
            get {
                return ResourceManager.GetString("PlayerLimitReachedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified player was not found..
        /// </summary>
        public static string PlayerNotFoundMessageLabel {
            get {
                return ResourceManager.GetString("PlayerNotFoundMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player doesn&apos;t belong to the lobby..
        /// </summary>
        public static string PlayerNotInLobbyMessageLabel {
            get {
                return ResourceManager.GetString("PlayerNotInLobbyMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing the player report. Please try again or contact an administrator..
        /// </summary>
        public static string PlayerReportFailedMessageLabel {
            get {
                return ResourceManager.GetString("PlayerReportFailedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player was not ready..
        /// </summary>
        public static string PlayerWereNotReadyMessageLabel {
            get {
                return ResourceManager.GetString("PlayerWereNotReadyMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error while retrieving profile..
        /// </summary>
        public static string ProfileFetchFailedMessageLabel {
            get {
                return ResourceManager.GetString("ProfileFetchFailedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile information has not been loaded..
        /// </summary>
        public static string ProfileNotLoadedMessageLabel {
            get {
                return ResourceManager.GetString("ProfileNotLoadedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error while updating profile..
        /// </summary>
        public static string ProfileUpdateFailedMessageLabel {
            get {
                return ResourceManager.GetString("ProfileUpdateFailedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your purchase..
        /// </summary>
        public static string PurchaseProcessingErrorMessageLabel {
            get {
                return ResourceManager.GetString("PurchaseProcessingErrorMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many requests in a short time, please hold on....
        /// </summary>
        public static string RateLimitExceededMessageLabel {
            get {
                return ResourceManager.GetString("RateLimitExceededMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registration information was lost because too much time has passed. Please try again..
        /// </summary>
        public static string RegistrationDataLostMessageLabel {
            get {
                return ResourceManager.GetString("RegistrationDataLostMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error in the registration module..
        /// </summary>
        public static string RegistrationInternalErrorMessageLabel {
            get {
                return ResourceManager.GetString("RegistrationInternalErrorMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error in the reports module..
        /// </summary>
        public static string ReportInternalErrorMessageLabel {
            get {
                return ResourceManager.GetString("ReportInternalErrorMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing the reward..
        /// </summary>
        public static string RewardProcessingErrorMessageLabel {
            get {
                return ResourceManager.GetString("RewardProcessingErrorMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error serializing or deserializing objects..
        /// </summary>
        public static string SerializationErrorMessageLabel {
            get {
                return ResourceManager.GetString("SerializationErrorMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing the server, please contact an administrator..
        /// </summary>
        public static string ServiceInitializationFailedMessageLabel {
            get {
                return ResourceManager.GetString("ServiceInitializationFailedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session has expired, please log in again..
        /// </summary>
        public static string SessionExpiredMessageLabel {
            get {
                return ResourceManager.GetString("SessionExpiredMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error in the shop module..
        /// </summary>
        public static string ShopInternalErrorMessageLabel {
            get {
                return ResourceManager.GetString("ShopInternalErrorMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL must belong to the {0} domain..
        /// </summary>
        public static string SocialLinkDomainMessageLabel {
            get {
                return ResourceManager.GetString("SocialLinkDomainMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} link is not a valid URL..
        /// </summary>
        public static string SocialLinkFormatMessageLabel {
            get {
                return ResourceManager.GetString("SocialLinkFormatMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user hasn&apos;t configured this social network. Please try another one..
        /// </summary>
        public static string SocialNetworkNotConfiguredMessageLabel {
            get {
                return ResourceManager.GetString("SocialNetworkNotConfiguredMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when executing an SQL query..
        /// </summary>
        public static string SqlErrorMessageLabel {
            get {
                return ResourceManager.GetString("SqlErrorMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout exceeded..
        /// </summary>
        public static string TimeoutMessageLabel {
            get {
                return ResourceManager.GetString("TimeoutMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed or unconfirmed transaction..
        /// </summary>
        public static string TransactionFailedMessageLabel {
            get {
                return ResourceManager.GetString("TransactionFailedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link couldn&apos;t be opened. Please try again..
        /// </summary>
        public static string UnableToOpenLinkMessageLabel {
            get {
                return ResourceManager.GetString("UnableToOpenLinkMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access..
        /// </summary>
        public static string UnauthorizedAccessMessageLabel {
            get {
                return ResourceManager.GetString("UnauthorizedAccessMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception..
        /// </summary>
        public static string UnhandledExceptionMessageLabel {
            get {
                return ResourceManager.GetString("UnhandledExceptionMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error, please contact the support team..
        /// </summary>
        public static string UnknownErrorMessageLabel {
            get {
                return ResourceManager.GetString("UnknownErrorMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unstable connection detected..
        /// </summary>
        public static string UnstableConnectionMessageLabel {
            get {
                return ResourceManager.GetString("UnstableConnectionMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is not logged in..
        /// </summary>
        public static string UserNotConnectedMessageLabel {
            get {
                return ResourceManager.GetString("UserNotConnectedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data validation failed..
        /// </summary>
        public static string ValidationFailedMessageLabel {
            get {
                return ResourceManager.GetString("ValidationFailedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification code is not valid..
        /// </summary>
        public static string VerificationCodeInvalidMessageLabel {
            get {
                return ResourceManager.GetString("VerificationCodeInvalidMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password doesn&apos;t match the minimum security requirements. Please fix it before continuing..
        /// </summary>
        public static string WeakPasswordMessageLabel {
            get {
                return ResourceManager.GetString("WeakPasswordMessageLabel", resourceCulture);
            }
        }
    }
}
