//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnoLisClient.UI.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FriendsList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FriendsList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnoLisClient.UI.Properties.Langs.FriendsList", typeof(FriendsList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add friend.
        /// </summary>
        public static string AddFriendButton {
            get {
                return ResourceManager.GetString("AddFriendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your friend&apos;s nickname to add them to the list..
        /// </summary>
        public static string EnterNicknameMessageLabel {
            get {
                return ResourceManager.GetString("EnterNicknameMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been removed from your friends list..
        /// </summary>
        public static string FriendRemovedMessageLabel {
            get {
                return ResourceManager.GetString("FriendRemovedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has accepted your friend request..
        /// </summary>
        public static string FriendRequestAcceptedLabel {
            get {
                return ResourceManager.GetString("FriendRequestAcceptedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve sent a friend request to {0}..
        /// </summary>
        public static string FriendRequestSentLabel {
            get {
                return ResourceManager.GetString("FriendRequestSentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My friends.
        /// </summary>
        public static string MyFriendsLabel {
            get {
                return ResourceManager.GetString("MyFriendsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been successfully blocked..
        /// </summary>
        public static string PlayerBlockedMessageLabel {
            get {
                return ResourceManager.GetString("PlayerBlockedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been successfully unblocked..
        /// </summary>
        public static string PlayerUnblockedMessageLabel {
            get {
                return ResourceManager.GetString("PlayerUnblockedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove {0} from your friends list?.
        /// </summary>
        public static string RemoveFriendMessageLabel {
            get {
                return ResourceManager.GetString("RemoveFriendMessageLabel", resourceCulture);
            }
        }
    }
}
