//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnoLisClient.UI.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnoLisClient.UI.Properties.Langs.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNO-LIS!.
        /// </summary>
        public static string AppNameLabel {
            get {
                return ResourceManager.GetString("AppNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string ChatLabel {
            get {
                return ResourceManager.GetString("ChatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string CodeLabel {
            get {
                return ResourceManager.GetString("CodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coins Revo.
        /// </summary>
        public static string CoinsLabel {
            get {
                return ResourceManager.GetString("CoinsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string ConfirmationLabel {
            get {
                return ResourceManager.GetString("ConfirmationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve sent you a confirmation code to your email. Please enter it below:.
        /// </summary>
        public static string ConfirmationMessageLabel {
            get {
                return ResourceManager.GetString("ConfirmationMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright Mauricio &amp; Erickmel.
        /// </summary>
        public static string CopyrightLabel {
            get {
                return ResourceManager.GetString("CopyrightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitLabel {
            get {
                return ResourceManager.GetString("ExitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string FriendsListLabel {
            get {
                return ResourceManager.GetString("FriendsListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game settings.
        /// </summary>
        public static string GameSettingsLabel {
            get {
                return ResourceManager.GetString("GameSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global points.
        /// </summary>
        public static string GlobalPointsColumn {
            get {
                return ResourceManager.GetString("GlobalPointsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go!.
        /// </summary>
        public static string GoButton {
            get {
                return ResourceManager.GetString("GoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string GuestLabel {
            get {
                return ResourceManager.GetString("GuestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to play?.
        /// </summary>
        public static string HowToPlayLabel {
            get {
                return ResourceManager.GetString("HowToPlayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches played.
        /// </summary>
        public static string MatchesPlayedColumn {
            get {
                return ResourceManager.GetString("MatchesPlayedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string MessagePlaceholderLabel {
            get {
                return ResourceManager.GetString("MessagePlaceholderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoButton {
            get {
                return ResourceManager.GetString("NoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game is currently unavailable, please try again later..
        /// </summary>
        public static string NoConnectionMessageLabel {
            get {
                return ResourceManager.GetString("NoConnectionMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAY!.
        /// </summary>
        public static string PlayButton {
            get {
                return ResourceManager.GetString("PlayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ProfileLabel {
            get {
                return ResourceManager.GetString("ProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string ShopLabel {
            get {
                return ResourceManager.GetString("ShopLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string StatisticsLabel {
            get {
                return ResourceManager.GetString("StatisticsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string SuccessLabel {
            get {
                return ResourceManager.GetString("SuccessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TitlePlaceholderLabel {
            get {
                return ResourceManager.GetString("TitlePlaceholderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful.
        /// </summary>
        public static string UnsuccessfulLabel {
            get {
                return ResourceManager.GetString("UnsuccessfulLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string VolumeLabel {
            get {
                return ResourceManager.GetString("VolumeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string WarningLabel {
            get {
                return ResourceManager.GetString("WarningLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win rate.
        /// </summary>
        public static string WinRateColumn {
            get {
                return ResourceManager.GetString("WinRateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesButton {
            get {
                return ResourceManager.GetString("YesButton", resourceCulture);
            }
        }
    }
}
