//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnoLisClient.UI.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lobby {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lobby() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnoLisClient.UI.Properties.Langs.Lobby", typeof(Lobby).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match {0} successfully created..
        /// </summary>
        public static string LobbyCreatedSuccessfullyLabel {
            get {
                return ResourceManager.GetString("LobbyCreatedSuccessfullyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New message received..
        /// </summary>
        public static string MessageRetrievedLabel {
            get {
                return ResourceManager.GetString("MessageRetrievedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat message sent successfully..
        /// </summary>
        public static string MessageSentSuccessfullyLabel {
            get {
                return ResourceManager.GetString("MessageSentSuccessfullyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New message sent successfully..
        /// </summary>
        public static string NewMessageSentLabel {
            get {
                return ResourceManager.GetString("NewMessageSentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has joined the match..
        /// </summary>
        public static string PlayerJoinedLabel {
            get {
                return ResourceManager.GetString("PlayerJoinedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has left the match..
        /// </summary>
        public static string PlayerLeftLabel {
            get {
                return ResourceManager.GetString("PlayerLeftLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not ready..
        /// </summary>
        public static string PlayerNotReadyLabel {
            get {
                return ResourceManager.GetString("PlayerNotReadyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is ready..
        /// </summary>
        public static string PlayerReadyLabel {
            get {
                return ResourceManager.GetString("PlayerReadyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READY!.
        /// </summary>
        public static string ReadyButton {
            get {
                return ResourceManager.GetString("ReadyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START!.
        /// </summary>
        public static string StartButton {
            get {
                return ResourceManager.GetString("StartButton", resourceCulture);
            }
        }
    }
}
