//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnoLisClient.UI.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Match {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Match() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnoLisClient.UI.Properties.Langs.Match", typeof(Match).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has drawn {1}..
        /// </summary>
        public static string CardDrawnMessageLabel {
            get {
                return ResourceManager.GetString("CardDrawnMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Color.
        /// </summary>
        public static string ChooseColorLabel {
            get {
                return ResourceManager.GetString("ChooseColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string ColorBlue {
            get {
                return ResourceManager.GetString("ColorBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} changed the color to {1}..
        /// </summary>
        public static string ColorChangedMessageLabel {
            get {
                return ResourceManager.GetString("ColorChangedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string ColorGreen {
            get {
                return ResourceManager.GetString("ColorGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string ColorRed {
            get {
                return ResourceManager.GetString("ColorRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string ColorYellow {
            get {
                return ResourceManager.GetString("ColorYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the reason for the report:.
        /// </summary>
        public static string DescriptionReportLabel {
            get {
                return ResourceManager.GetString("DescriptionReportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw a card.
        /// </summary>
        public static string DrawCardTooltip {
            get {
                return ResourceManager.GetString("DrawCardTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to leave the match?.
        /// </summary>
        public static string ExitMatchConfirmationLabel {
            get {
                return ResourceManager.GetString("ExitMatchConfirmationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game notification!.
        /// </summary>
        public static string GameNotificationMessageLabel {
            get {
                return ResourceManager.GetString("GameNotificationMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The move you made is invalid..
        /// </summary>
        public static string InvalidMoveMessageLabel {
            get {
                return ResourceManager.GetString("InvalidMoveMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item used!.
        /// </summary>
        public static string ItemUsedLabel {
            get {
                return ResourceManager.GetString("ItemUsedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} used {1}..
        /// </summary>
        public static string ItemUsedMessageLabel {
            get {
                return ResourceManager.GetString("ItemUsedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game is over..
        /// </summary>
        public static string MatchOverLabel {
            get {
                return ResourceManager.GetString("MatchOverLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Results.
        /// </summary>
        public static string MatchResultsLabel {
            get {
                return ResourceManager.GetString("MatchResultsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result of the match was recorded correctly..
        /// </summary>
        public static string MatchResultsRecordedMessageLabel {
            get {
                return ResourceManager.GetString("MatchResultsRecordedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting game....
        /// </summary>
        public static string MatchStartedLabel {
            get {
                return ResourceManager.GetString("MatchStartedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsLabel {
            get {
                return ResourceManager.GetString("OptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        public static string PlaceResultsColumn {
            get {
                return ResourceManager.GetString("PlaceResultsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been banned due to multiple reports, time remaining: {0}.
        /// </summary>
        public static string PlayerBannedMessageLabel {
            get {
                return ResourceManager.GetString("PlayerBannedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been successfully blocked..
        /// </summary>
        public static string PlayerBlockedMessageLabel {
            get {
                return ResourceManager.GetString("PlayerBlockedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} said UNO!.
        /// </summary>
        public static string PlayerDeclaredUnoMessageLabel {
            get {
                return ResourceManager.GetString("PlayerDeclaredUnoMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was kicked out of the game..
        /// </summary>
        public static string PlayerKickedMessageLabel {
            get {
                return ResourceManager.GetString("PlayerKickedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string PlayerNameColumn {
            get {
                return ResourceManager.GetString("PlayerNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been successfully reported..
        /// </summary>
        public static string PlayerReportedMessageLabel {
            get {
                return ResourceManager.GetString("PlayerReportedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string RankColumn {
            get {
                return ResourceManager.GetString("RankColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report player.
        /// </summary>
        public static string ReportPlayerLabel {
            get {
                return ResourceManager.GetString("ReportPlayerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string ScoreColumn {
            get {
                return ResourceManager.GetString("ScoreColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which player do you want to report?.
        /// </summary>
        public static string SelectReportPlayer {
            get {
                return ResourceManager.GetString("SelectReportPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now playing:.
        /// </summary>
        public static string TurnLabel {
            get {
                return ResourceManager.GetString("TurnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player {0} has won!.
        /// </summary>
        public static string WinnerLabel {
            get {
                return ResourceManager.GetString("WinnerLabel", resourceCulture);
            }
        }
    }
}
