//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnoLisClient.UI.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Profile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Profile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnoLisClient.UI.Properties.Langs.Profile", typeof(Profile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change avatar.
        /// </summary>
        public static string ChangeAvatarButton {
            get {
                return ResourceManager.GetString("ChangeAvatarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an avatar.
        /// </summary>
        public static string ChangeAvatarLabel {
            get {
                return ResourceManager.GetString("ChangeAvatarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change date.
        /// </summary>
        public static string ChangeDataButton {
            get {
                return ResourceManager.GetString("ChangeDataButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epic skins.
        /// </summary>
        public static string EpicSkinsLabel {
            get {
                return ResourceManager.GetString("EpicSkinsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legendary skins.
        /// </summary>
        public static string LegendarySkinsLabel {
            get {
                return ResourceManager.GetString("LegendarySkinsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loses.
        /// </summary>
        public static string LosesColumn {
            get {
                return ResourceManager.GetString("LosesColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social media.
        /// </summary>
        public static string SocialMediaLabel {
            get {
                return ResourceManager.GetString("SocialMediaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special skins.
        /// </summary>
        public static string SpecialSkinsLabel {
            get {
                return ResourceManager.GetString("SpecialSkinsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins.
        /// </summary>
        public static string WinsColumn {
            get {
                return ResourceManager.GetString("WinsColumn", resourceCulture);
            }
        }
    }
}
