//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnoLisClient.UI.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Shop {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shop() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnoLisClient.UI.Properties.Langs.Shop", typeof(Shop).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar shop.
        /// </summary>
        public static string AvatarShopLabel {
            get {
                return ResourceManager.GetString("AvatarShopLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string BuyButton {
            get {
                return ResourceManager.GetString("BuyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epic box.
        /// </summary>
        public static string EpicBoxLabel {
            get {
                return ResourceManager.GetString("EpicBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legendary box.
        /// </summary>
        public static string LegendaryBoxLabel {
            get {
                return ResourceManager.GetString("LegendaryBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIS Boxes.
        /// </summary>
        public static string LisBoxesLabel {
            get {
                return ResourceManager.GetString("LisBoxesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are the icons you can get, are you sure you want to proceed?.
        /// </summary>
        public static string PurchaseConfirmationLabel {
            get {
                return ResourceManager.GetString("PurchaseConfirmationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase completed successfully..
        /// </summary>
        public static string PurchaseSuccessfulLabel {
            get {
                return ResourceManager.GetString("PurchaseSuccessfulLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revo Coins.
        /// </summary>
        public static string RevoCoinsLabel {
            get {
                return ResourceManager.GetString("RevoCoinsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward &apos;{0}&apos; obtained..
        /// </summary>
        public static string RewardObtainedLabel {
            get {
                return ResourceManager.GetString("RewardObtainedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congrats, you&apos;ve got: {0}.
        /// </summary>
        public static string RewardShopLabel {
            get {
                return ResourceManager.GetString("RewardShopLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special box.
        /// </summary>
        public static string SpecialBoxLabel {
            get {
                return ResourceManager.GetString("SpecialBoxLabel", resourceCulture);
            }
        }
    }
}
