//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnoLisClient.UI.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SignIn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SignIn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnoLisClient.UI.Properties.Langs.SignIn", typeof(SignIn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string FullNameLabel {
            get {
                return ResourceManager.GetString("FullNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string NicknameLabel {
            get {
                return ResourceManager.GetString("NicknameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not registered yet? Sign up here..
        /// </summary>
        public static string NotRegisteredLabel {
            get {
                return ResourceManager.GetString("NotRegisteredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password requirements.
        /// </summary>
        public static string PasswordRequirementsHeaderLabel {
            get {
                return ResourceManager.GetString("PasswordRequirementsHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ◆ At least one capital letter (A-Z)..
        /// </summary>
        public static string PasswordValidationCapitalLabel {
            get {
                return ResourceManager.GetString("PasswordValidationCapitalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain:.
        /// </summary>
        public static string PasswordValidationHeaderLabel {
            get {
                return ResourceManager.GetString("PasswordValidationHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ◆ Between 8 and 255 characters..
        /// </summary>
        public static string PasswordValidationLengthLabel {
            get {
                return ResourceManager.GetString("PasswordValidationLengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ◆ At least lowercase letter (a-z)..
        /// </summary>
        public static string PasswordValidationLowerLabel {
            get {
                return ResourceManager.GetString("PasswordValidationLowerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ◆ At least one number (0-9)..
        /// </summary>
        public static string PasswordValidationNumberLabel {
            get {
                return ResourceManager.GetString("PasswordValidationNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ◆ At least one special character (@, $, !, %, *, ?, &amp;, -, _)..
        /// </summary>
        public static string PasswordValidationSpecialCharLabel {
            get {
                return ResourceManager.GetString("PasswordValidationSpecialCharLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play as guest.
        /// </summary>
        public static string PlayAsGuestButton {
            get {
                return ResourceManager.GetString("PlayAsGuestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register to UNO-LIS!.
        /// </summary>
        public static string RegisterLabel {
            get {
                return ResourceManager.GetString("RegisterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Didn&apos;t receive the code? Resend..
        /// </summary>
        public static string ResendVerificationCodeLabel {
            get {
                return ResourceManager.GetString("ResendVerificationCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewrite password.
        /// </summary>
        public static string RewritedPasswordLabel {
            get {
                return ResourceManager.GetString("RewritedPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignInButton {
            get {
                return ResourceManager.GetString("SignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to            Login successful. 
        ///Welcome to UNO-LIS {0}!.
        /// </summary>
        public static string UserLoggedInSuccessfullyLabel {
            get {
                return ResourceManager.GetString("UserLoggedInSuccessfullyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully logged out..
        /// </summary>
        public static string UserLoggedOutSuccessfullyLabel {
            get {
                return ResourceManager.GetString("UserLoggedOutSuccessfullyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully registered, welcome to UNO-LIS!.
        /// </summary>
        public static string UserRegisteredSuccessfullyLabel {
            get {
                return ResourceManager.GetString("UserRegisteredSuccessfullyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code sent successfully..
        /// </summary>
        public static string VerificationCodeSentLabel {
            get {
                return ResourceManager.GetString("VerificationCodeSentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to UNO-LIS!.
        /// </summary>
        public static string WelcomeLabel {
            get {
                return ResourceManager.GetString("WelcomeLabel", resourceCulture);
            }
        }
    }
}
