//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnoLisClient.UI.UnoLisServerReference.PartyClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JoinPartyRequest", Namespace="http://schemas.datacontract.org/2004/07/UnoLisServer.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class JoinPartyRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JoinCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JoinCode {
            get {
                return this.JoinCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.JoinCodeField, value) != true)) {
                    this.JoinCodeField = value;
                    this.RaisePropertyChanged("JoinCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartyActionData", Namespace="http://schemas.datacontract.org/2004/07/UnoLisServer.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class PartyActionData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsReadyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PartyIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsReady {
            get {
                return this.IsReadyField;
            }
            set {
                if ((this.IsReadyField.Equals(value) != true)) {
                    this.IsReadyField = value;
                    this.RaisePropertyChanged("IsReady");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PartyId {
            get {
                return this.PartyIdField;
            }
            set {
                if ((this.PartyIdField.Equals(value) != true)) {
                    this.PartyIdField = value;
                    this.RaisePropertyChanged("PartyId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UnoLisServerReference.PartyClient.IPartyClientManager", CallbackContract=typeof(UnoLisClient.UI.UnoLisServerReference.PartyClient.IPartyClientManagerCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IPartyClientManager {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPartyClientManager/JoinParty")]
        void JoinParty(UnoLisClient.UI.UnoLisServerReference.PartyClient.JoinPartyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPartyClientManager/JoinParty")]
        System.Threading.Tasks.Task JoinPartyAsync(UnoLisClient.UI.UnoLisServerReference.PartyClient.JoinPartyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPartyClientManager/LeaveParty")]
        void LeaveParty(UnoLisClient.UI.UnoLisServerReference.PartyClient.PartyActionData data);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPartyClientManager/LeaveParty")]
        System.Threading.Tasks.Task LeavePartyAsync(UnoLisClient.UI.UnoLisServerReference.PartyClient.PartyActionData data);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPartyClientManager/SetReadyStatus")]
        void SetReadyStatus(UnoLisClient.UI.UnoLisServerReference.PartyClient.PartyActionData data);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPartyClientManager/SetReadyStatus")]
        System.Threading.Tasks.Task SetReadyStatusAsync(UnoLisClient.UI.UnoLisServerReference.PartyClient.PartyActionData data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPartyClientManagerCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartyClientManager/JoinedSuccessfully", ReplyAction="http://tempuri.org/IPartyClientManager/JoinedSuccessfullyResponse")]
        void JoinedSuccessfully(int partyId, string hostNickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartyClientManager/JoinFailed", ReplyAction="http://tempuri.org/IPartyClientManager/JoinFailedResponse")]
        void JoinFailed(string reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartyClientManager/PlayerJoined", ReplyAction="http://tempuri.org/IPartyClientManager/PlayerJoinedResponse")]
        void PlayerJoined(string nickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartyClientManager/PlayerLeft", ReplyAction="http://tempuri.org/IPartyClientManager/PlayerLeftResponse")]
        void PlayerLeft(string nickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartyClientManager/PlayerReadyStatusChanged", ReplyAction="http://tempuri.org/IPartyClientManager/PlayerReadyStatusChangedResponse")]
        void PlayerReadyStatusChanged(string nickname, bool isReady);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartyClientManager/MatchStarting", ReplyAction="http://tempuri.org/IPartyClientManager/MatchStartingResponse")]
        void MatchStarting();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartyClientManager/PartyCancelled", ReplyAction="http://tempuri.org/IPartyClientManager/PartyCancelledResponse")]
        void PartyCancelled();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartyClientManager/PartyDisbanded", ReplyAction="http://tempuri.org/IPartyClientManager/PartyDisbandedResponse")]
        void PartyDisbanded();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPartyClientManagerChannel : UnoLisClient.UI.UnoLisServerReference.PartyClient.IPartyClientManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PartyClientManagerClient : System.ServiceModel.DuplexClientBase<UnoLisClient.UI.UnoLisServerReference.PartyClient.IPartyClientManager>, UnoLisClient.UI.UnoLisServerReference.PartyClient.IPartyClientManager {
        
        public PartyClientManagerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public PartyClientManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public PartyClientManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public PartyClientManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public PartyClientManagerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void JoinParty(UnoLisClient.UI.UnoLisServerReference.PartyClient.JoinPartyRequest request) {
            base.Channel.JoinParty(request);
        }
        
        public System.Threading.Tasks.Task JoinPartyAsync(UnoLisClient.UI.UnoLisServerReference.PartyClient.JoinPartyRequest request) {
            return base.Channel.JoinPartyAsync(request);
        }
        
        public void LeaveParty(UnoLisClient.UI.UnoLisServerReference.PartyClient.PartyActionData data) {
            base.Channel.LeaveParty(data);
        }
        
        public System.Threading.Tasks.Task LeavePartyAsync(UnoLisClient.UI.UnoLisServerReference.PartyClient.PartyActionData data) {
            return base.Channel.LeavePartyAsync(data);
        }
        
        public void SetReadyStatus(UnoLisClient.UI.UnoLisServerReference.PartyClient.PartyActionData data) {
            base.Channel.SetReadyStatus(data);
        }
        
        public System.Threading.Tasks.Task SetReadyStatusAsync(UnoLisClient.UI.UnoLisServerReference.PartyClient.PartyActionData data) {
            return base.Channel.SetReadyStatusAsync(data);
        }
    }
}
