//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnoLisClient.UI.UnoLisServerReference.Confirmation {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UnoLisServerReference.Confirmation.IConfirmationManager", CallbackContract=typeof(UnoLisClient.UI.UnoLisServerReference.Confirmation.IConfirmationManagerCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IConfirmationManager {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IConfirmationManager/ConfirmCode")]
        void ConfirmCode(string email, string code);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IConfirmationManager/ConfirmCode")]
        System.Threading.Tasks.Task ConfirmCodeAsync(string email, string code);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IConfirmationManager/ResendConfirmationCode")]
        void ResendConfirmationCode(string email);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IConfirmationManager/ResendConfirmationCode")]
        System.Threading.Tasks.Task ResendConfirmationCodeAsync(string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConfirmationManagerCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfirmationManager/ConfirmationResponse", ReplyAction="http://tempuri.org/IConfirmationManager/ConfirmationResponseResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UnoLisServer.Common.Enums.MessageCode))]
        void ConfirmationResponse(UnoLisServer.Common.Models.ServiceResponse<object> response);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfirmationManager/ResendCodeResponse", ReplyAction="http://tempuri.org/IConfirmationManager/ResendCodeResponseResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UnoLisServer.Common.Enums.MessageCode))]
        void ResendCodeResponse(UnoLisServer.Common.Models.ServiceResponse<object> response);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConfirmationManagerChannel : UnoLisClient.UI.UnoLisServerReference.Confirmation.IConfirmationManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConfirmationManagerClient : System.ServiceModel.DuplexClientBase<UnoLisClient.UI.UnoLisServerReference.Confirmation.IConfirmationManager>, UnoLisClient.UI.UnoLisServerReference.Confirmation.IConfirmationManager {
        
        public ConfirmationManagerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ConfirmationManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ConfirmationManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ConfirmationManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ConfirmationManagerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void ConfirmCode(string email, string code) {
            base.Channel.ConfirmCode(email, code);
        }
        
        public System.Threading.Tasks.Task ConfirmCodeAsync(string email, string code) {
            return base.Channel.ConfirmCodeAsync(email, code);
        }
        
        public void ResendConfirmationCode(string email) {
            base.Channel.ResendConfirmationCode(email);
        }
        
        public System.Threading.Tasks.Task ResendConfirmationCodeAsync(string email) {
            return base.Channel.ResendConfirmationCodeAsync(email);
        }
    }
}
