//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnoLisClient.Logic.UnoLisServerReference.Leaderboards {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LeaderboardEntry", Namespace="http://schemas.datacontract.org/2004/07/UnoLisServer.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class LeaderboardEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GlobalPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchesPlayedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WinRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WinsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GlobalPoints {
            get {
                return this.GlobalPointsField;
            }
            set {
                if ((this.GlobalPointsField.Equals(value) != true)) {
                    this.GlobalPointsField = value;
                    this.RaisePropertyChanged("GlobalPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchesPlayed {
            get {
                return this.MatchesPlayedField;
            }
            set {
                if ((this.MatchesPlayedField.Equals(value) != true)) {
                    this.MatchesPlayedField = value;
                    this.RaisePropertyChanged("MatchesPlayed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rank {
            get {
                return this.RankField;
            }
            set {
                if ((this.RankField.Equals(value) != true)) {
                    this.RankField = value;
                    this.RaisePropertyChanged("Rank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WinRate {
            get {
                return this.WinRateField;
            }
            set {
                if ((object.ReferenceEquals(this.WinRateField, value) != true)) {
                    this.WinRateField = value;
                    this.RaisePropertyChanged("WinRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Wins {
            get {
                return this.WinsField;
            }
            set {
                if ((this.WinsField.Equals(value) != true)) {
                    this.WinsField = value;
                    this.RaisePropertyChanged("Wins");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UnoLisServerReference.Leaderboards.ILeaderboardsManager")]
    public interface ILeaderboardsManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeaderboardsManager/GetGlobalLeaderboard", ReplyAction="http://tempuri.org/ILeaderboardsManager/GetGlobalLeaderboardResponse")]
        UnoLisServer.Common.Models.ServiceResponse<UnoLisClient.Logic.UnoLisServerReference.Leaderboards.LeaderboardEntry[]> GetGlobalLeaderboard();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeaderboardsManager/GetGlobalLeaderboard", ReplyAction="http://tempuri.org/ILeaderboardsManager/GetGlobalLeaderboardResponse")]
        System.Threading.Tasks.Task<UnoLisServer.Common.Models.ServiceResponse<UnoLisClient.Logic.UnoLisServerReference.Leaderboards.LeaderboardEntry[]>> GetGlobalLeaderboardAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILeaderboardsManagerChannel : UnoLisClient.Logic.UnoLisServerReference.Leaderboards.ILeaderboardsManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LeaderboardsManagerClient : System.ServiceModel.ClientBase<UnoLisClient.Logic.UnoLisServerReference.Leaderboards.ILeaderboardsManager>, UnoLisClient.Logic.UnoLisServerReference.Leaderboards.ILeaderboardsManager {
        
        public LeaderboardsManagerClient() {
        }
        
        public LeaderboardsManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LeaderboardsManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeaderboardsManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeaderboardsManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UnoLisServer.Common.Models.ServiceResponse<UnoLisClient.Logic.UnoLisServerReference.Leaderboards.LeaderboardEntry[]> GetGlobalLeaderboard() {
            return base.Channel.GetGlobalLeaderboard();
        }
        
        public System.Threading.Tasks.Task<UnoLisServer.Common.Models.ServiceResponse<UnoLisClient.Logic.UnoLisServerReference.Leaderboards.LeaderboardEntry[]>> GetGlobalLeaderboardAsync() {
            return base.Channel.GetGlobalLeaderboardAsync();
        }
    }
}
