//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnoLisClient.Logic.UnoLisServerReference.Matchmaking {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchSettings", Namespace="http://schemas.datacontract.org/2004/07/UnoLisServer.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class MatchSettings : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HostNicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxPlayersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UseSpecialRulesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HostNickname {
            get {
                return this.HostNicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.HostNicknameField, value) != true)) {
                    this.HostNicknameField = value;
                    this.RaisePropertyChanged("HostNickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxPlayers {
            get {
                return this.MaxPlayersField;
            }
            set {
                if ((this.MaxPlayersField.Equals(value) != true)) {
                    this.MaxPlayersField = value;
                    this.RaisePropertyChanged("MaxPlayers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseSpecialRules {
            get {
                return this.UseSpecialRulesField;
            }
            set {
                if ((this.UseSpecialRulesField.Equals(value) != true)) {
                    this.UseSpecialRulesField = value;
                    this.RaisePropertyChanged("UseSpecialRules");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateMatchResponse", Namespace="http://schemas.datacontract.org/2004/07/UnoLisServer.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class CreateMatchResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LobbyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LobbyCode {
            get {
                return this.LobbyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LobbyCodeField, value) != true)) {
                    this.LobbyCodeField = value;
                    this.RaisePropertyChanged("LobbyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JoinMatchResponse", Namespace="http://schemas.datacontract.org/2004/07/UnoLisServer.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class JoinMatchResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LobbyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LobbyCode {
            get {
                return this.LobbyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LobbyCodeField, value) != true)) {
                    this.LobbyCodeField = value;
                    this.RaisePropertyChanged("LobbyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UnoLisServerReference.Matchmaking.IMatchmakingManager")]
    public interface IMatchmakingManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingManager/CreateMatch", ReplyAction="http://tempuri.org/IMatchmakingManager/CreateMatchResponse")]
        UnoLisClient.Logic.UnoLisServerReference.Matchmaking.CreateMatchResponse CreateMatch(UnoLisClient.Logic.UnoLisServerReference.Matchmaking.MatchSettings settings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingManager/CreateMatch", ReplyAction="http://tempuri.org/IMatchmakingManager/CreateMatchResponse")]
        System.Threading.Tasks.Task<UnoLisClient.Logic.UnoLisServerReference.Matchmaking.CreateMatchResponse> CreateMatchAsync(UnoLisClient.Logic.UnoLisServerReference.Matchmaking.MatchSettings settings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingManager/JoinMatch", ReplyAction="http://tempuri.org/IMatchmakingManager/JoinMatchResponse")]
        UnoLisClient.Logic.UnoLisServerReference.Matchmaking.JoinMatchResponse JoinMatch(string lobbyCode, string nickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingManager/JoinMatch", ReplyAction="http://tempuri.org/IMatchmakingManager/JoinMatchResponse")]
        System.Threading.Tasks.Task<UnoLisClient.Logic.UnoLisServerReference.Matchmaking.JoinMatchResponse> JoinMatchAsync(string lobbyCode, string nickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingManager/SendInvitations", ReplyAction="http://tempuri.org/IMatchmakingManager/SendInvitationsResponse")]
        bool SendInvitations(string lobbyCode, string senderNickname, string[] invitedNicknames);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingManager/SendInvitations", ReplyAction="http://tempuri.org/IMatchmakingManager/SendInvitationsResponse")]
        System.Threading.Tasks.Task<bool> SendInvitationsAsync(string lobbyCode, string senderNickname, string[] invitedNicknames);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchmakingManagerChannel : UnoLisClient.Logic.UnoLisServerReference.Matchmaking.IMatchmakingManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatchmakingManagerClient : System.ServiceModel.ClientBase<UnoLisClient.Logic.UnoLisServerReference.Matchmaking.IMatchmakingManager>, UnoLisClient.Logic.UnoLisServerReference.Matchmaking.IMatchmakingManager {
        
        public MatchmakingManagerClient() {
        }
        
        public MatchmakingManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MatchmakingManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatchmakingManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatchmakingManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UnoLisClient.Logic.UnoLisServerReference.Matchmaking.CreateMatchResponse CreateMatch(UnoLisClient.Logic.UnoLisServerReference.Matchmaking.MatchSettings settings) {
            return base.Channel.CreateMatch(settings);
        }
        
        public System.Threading.Tasks.Task<UnoLisClient.Logic.UnoLisServerReference.Matchmaking.CreateMatchResponse> CreateMatchAsync(UnoLisClient.Logic.UnoLisServerReference.Matchmaking.MatchSettings settings) {
            return base.Channel.CreateMatchAsync(settings);
        }
        
        public UnoLisClient.Logic.UnoLisServerReference.Matchmaking.JoinMatchResponse JoinMatch(string lobbyCode, string nickname) {
            return base.Channel.JoinMatch(lobbyCode, nickname);
        }
        
        public System.Threading.Tasks.Task<UnoLisClient.Logic.UnoLisServerReference.Matchmaking.JoinMatchResponse> JoinMatchAsync(string lobbyCode, string nickname) {
            return base.Channel.JoinMatchAsync(lobbyCode, nickname);
        }
        
        public bool SendInvitations(string lobbyCode, string senderNickname, string[] invitedNicknames) {
            return base.Channel.SendInvitations(lobbyCode, senderNickname, invitedNicknames);
        }
        
        public System.Threading.Tasks.Task<bool> SendInvitationsAsync(string lobbyCode, string senderNickname, string[] invitedNicknames) {
            return base.Channel.SendInvitationsAsync(lobbyCode, senderNickname, invitedNicknames);
        }
    }
}
