//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnoLisClient.Logic.UnoLisServerReference.Avatar {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerAvatar", Namespace="http://schemas.datacontract.org/2004/07/UnoLisServer.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class PlayerAvatar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvatarIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvatarNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSelectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsUnlockedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RarityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvatarId {
            get {
                return this.AvatarIdField;
            }
            set {
                if ((this.AvatarIdField.Equals(value) != true)) {
                    this.AvatarIdField = value;
                    this.RaisePropertyChanged("AvatarId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvatarName {
            get {
                return this.AvatarNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarNameField, value) != true)) {
                    this.AvatarNameField = value;
                    this.RaisePropertyChanged("AvatarName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSelected {
            get {
                return this.IsSelectedField;
            }
            set {
                if ((this.IsSelectedField.Equals(value) != true)) {
                    this.IsSelectedField = value;
                    this.RaisePropertyChanged("IsSelected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsUnlocked {
            get {
                return this.IsUnlockedField;
            }
            set {
                if ((this.IsUnlockedField.Equals(value) != true)) {
                    this.IsUnlockedField = value;
                    this.RaisePropertyChanged("IsUnlocked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rarity {
            get {
                return this.RarityField;
            }
            set {
                if ((object.ReferenceEquals(this.RarityField, value) != true)) {
                    this.RarityField = value;
                    this.RaisePropertyChanged("Rarity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UnoLisServerReference.Avatar.IAvatarManager", CallbackContract=typeof(UnoLisClient.Logic.UnoLisServerReference.Avatar.IAvatarManagerCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IAvatarManager {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAvatarManager/GetPlayerAvatars")]
        void GetPlayerAvatars(string nickname);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAvatarManager/GetPlayerAvatars")]
        System.Threading.Tasks.Task GetPlayerAvatarsAsync(string nickname);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAvatarManager/SetPlayerAvatar")]
        void SetPlayerAvatar(string nickname, int newAvatarId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAvatarManager/SetPlayerAvatar")]
        System.Threading.Tasks.Task SetPlayerAvatarAsync(string nickname, int newAvatarId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAvatarManagerCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAvatarManager/AvatarsDataReceived", ReplyAction="http://tempuri.org/IAvatarManager/AvatarsDataReceivedResponse")]
        void AvatarsDataReceived(UnoLisServer.Common.Models.ServiceResponse<UnoLisClient.Logic.UnoLisServerReference.Avatar.PlayerAvatar[]> response);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAvatarManager/AvatarUpdateResponse", ReplyAction="http://tempuri.org/IAvatarManager/AvatarUpdateResponseResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UnoLisClient.Logic.UnoLisServerReference.Avatar.PlayerAvatar[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UnoLisClient.Logic.UnoLisServerReference.Avatar.PlayerAvatar))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UnoLisServer.Common.Enums.MessageCode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UnoLisServer.Common.Models.ServiceResponse<UnoLisClient.Logic.UnoLisServerReference.Avatar.PlayerAvatar[]>))]
        void AvatarUpdateResponse(UnoLisServer.Common.Models.ServiceResponse<object> response);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAvatarManagerChannel : UnoLisClient.Logic.UnoLisServerReference.Avatar.IAvatarManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AvatarManagerClient : System.ServiceModel.DuplexClientBase<UnoLisClient.Logic.UnoLisServerReference.Avatar.IAvatarManager>, UnoLisClient.Logic.UnoLisServerReference.Avatar.IAvatarManager {
        
        public AvatarManagerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public AvatarManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public AvatarManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AvatarManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AvatarManagerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void GetPlayerAvatars(string nickname) {
            base.Channel.GetPlayerAvatars(nickname);
        }
        
        public System.Threading.Tasks.Task GetPlayerAvatarsAsync(string nickname) {
            return base.Channel.GetPlayerAvatarsAsync(nickname);
        }
        
        public void SetPlayerAvatar(string nickname, int newAvatarId) {
            base.Channel.SetPlayerAvatar(nickname, newAvatarId);
        }
        
        public System.Threading.Tasks.Task SetPlayerAvatarAsync(string nickname, int newAvatarId) {
            return base.Channel.SetPlayerAvatarAsync(nickname, newAvatarId);
        }
    }
}
